#!/bin/sh

# This file should be linked onto /init 
# it should be started by kernel after initramfs installion.

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

for i in /etc/init.d/S*; do
  $i start 2>&1
done 
