#!/bin/sh

# Author: Fulup Ar Foll
# Object: Boot SuSE diskless client
# Date:   25-oct-2005

if test -f /etc/init.d/functions
then
 . /etc/init.d/functions
fi

set -x

echo mount devices from /etc/fstab
mount -n -a

echo network loopback
ifconfig lo 127.0.0.1 up

echo mount devices in /dev
udevd --daemon
udevstart

echo starting syslog
/sbin/syslogd -C 16 -L -R 10.10.11.1
