#!/bin/sh

# Author: Fulup Ar Foll
# Object: Boot SuSE diskless client
# Date:   25-oct-2005

if test -f /etc/init.d/functions
then
 . /etc/init.d/functions
fi


set -x

loadkeys /usr/share/kbd/keymaps/i386/azerty/fr-pc.map.gz
