#!/bin/sh

if test -f /etc/init.d/functions
then
 . /etc/init.d/functions
fi


# Module to load (ef_packet is needed for dhcp)
SF_MODULES="af_packet"

# Try to detect hardware modules dynmlicaly
HW_MODULES=`hwinfo --netcard | grep Driver: | awk '{print $2}'`

for MODULE in $SF_MODULES $HW_MODULES
do
  modprobe $MODULE
done

echo "Request eth0 IP@ by DHCP"
dhcpcd   eth0
